UI/MultiShop.WebUI/Areas/Admin/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using MultiShop.DTOLayer.DTOs.CatalogDTOs.ProductDetailDTOs;
using MultiShop.WebUI.Services.CatalogServices.ProductDetailServices;

namespace MultiShop.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/ProductDetail")]
    public class ProductDetailController : Controller
    {
        private readonly IProductDetailService _productDetailService;

        public ProductDetailController(IProductDetailService productDetailService)
        {
            _productDetailService = productDetailService;
        }

        [Route("UpdateProductDetail/{id}"), HttpGet]
        public async Task<IActionResult> UpdateProductDetail(string id, CancellationToken cancellationToken)
        {
            ViewBag.v1 = "Home";
            ViewBag.v2 = "Categories";
            ViewBag.v3 = "Update Product Detail";
            ViewBag.v0 = "Product Detail Operations";

            var responseGet = await _productDetailService.GetProductDetailByProductId(id, cancellationToken);
            if (responseGet != null)
            {
                return View(responseGet);
            }
            CreateProductDetailDTO createProductDetailDTO = new()
            {
                ProductID = id,
                ProductDescription = "",
                ProductInfo = ""
            };
            var responsePost = await _productDetailService.CreateProductDetailAsync(createProductDetailDTO, cancellationToken);
            if (responsePost.IsSuccessStatusCode)
            {
                return View();
            }
            return RedirectToAction("ProductListWithCategory", "Product", new { area = "Admin" });
        }

        [Route("UpdateProductDetail/{id}"), HttpPost]
        public async Task<IActionResult> UpdateProductDetail(UpdateProductDetailDTO updateProductDetailDTO, CancellationToken cancellationToken)
        {
            var response = await _productDetailService.UpdateProductDetailAsync(updateProductDetailDTO, cancellationToken);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("ProductListWithCategory", "Product", new { area = "Admin" });
            }
            return View();
        }
    }
}

UI/MultiShop.WebUI/Controllers/ProductListController.cs
using Microsoft.AspNetCore.Mvc;
using MultiShop.DTOLayer.DTOs.CommentDTOs;
using MultiShop.WebUI.Services.CommentServices;

namespace MultiShop.WebUI.Controllers
{
    public class ProductListController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ICommentService _commentService;

        public ProductListController(IHttpClientFactory httpClientFactory, ICommentService commentService)
        {
            _httpClientFactory = httpClientFactory;
            _commentService = commentService;
        }

        public IActionResult Index(string id)
        {
            ViewBag.CategoryId = id;
            return View();
        }

        public IActionResult ProductDetail(string id)
        {
            ViewBag.ProductId = id;
            return View();
        }

        [HttpGet]
        public PartialViewResult AddComment(string id)
        {
            ViewBag.ProductId = id;
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(CreateCommentDTO createCommentDTO, CancellationToken cancellationToken)
        {
            createCommentDTO.CommentID = Guid.NewGuid();
            createCommentDTO.ImageUrl = "";
            createCommentDTO.CreationDate = DateTime.Now;
            createCommentDTO.Status = false;
            createCommentDTO.ProductID = ViewBag.ProductId;
            createCommentDTO.Rating = 1;

            var response = await _commentService.CreateCommentAsync(createCommentDTO, cancellationToken);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

UI/MultiShop.WebUI/Views/ProductList/AddComment.cshtml
<div class="col-md-6">
    <h4 class="mb-4">Leave a review</h4>
    <small>Your email address will not be published. Required fields are marked *</small>
    <div class="d-flex my-3">
        <p class="mb-0 mr-2">Your Rating * :</p>
        <div class="text-primary">
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
        </div>
    </div>
    <form method="post" asp-action="AddComment" asp-controller="ProductList">
        <input type="hidden"  name="ProductID" value="@ViewBag.ProductId" />

        <div class="form-group">
            <label for="name"></label>
            <input type="text"  class="form-control" id="name" name="NameSurname">
        </div>
        <div class="form-group">
            <label for="email">Your Email *</label>
            <input type="email"  class="form-control" id="email" name="Email">
        </div>   
        <div class="form-group">
            <label for="message">Your Review *</label>
            <textarea id="message"  cols="30" rows="5" class="form-control" name="CommentDetail"></textarea>
        </div>
        <div class="form-group mb-0">
            <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
        </div>
    </form>
</div>

UI/MultiShop.WebUI/Views/ProductList/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/UILayout/_UILayout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shop List</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Shop Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-4">
            <!-- Price Start -->
            @await Component.InvokeAsync("_PriceFilterProductListComponentPartial")
            <!-- Price End -->
            <!-- Color Start -->
            @await Component.InvokeAsync("_ColorFilterProductListComponentPartial")
            <!-- Color End -->
            <!-- Size Start -->
            @await Component.InvokeAsync("_SizeFilterProductListComponentPartial")
            <!-- Size End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">
                @await Component.InvokeAsync("_SortFilterProductListComponentPartial")

                @await Component.InvokeAsync("_ProductsProductListComponentPartial", new { categoryId = ViewBag.CategoryId })
           
                @await Component.InvokeAsync("_PaginationProductListComponentPartial")
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

UI/MultiShop.WebUI/Views/ProductList/ProductDetail.cshtml
@{
    ViewData["Title"] = "ProductDetail";
    Layout = "~/Views/UILayout/_UILayout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shop List</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Shop Detail Start -->
<div class="container-fluid pb-5">
    <div class="row px-xl-5">

        @await Component.InvokeAsync("_ProductDetailImageSliderComponentPartial", new { productId = ViewBag.ProductId })
        @await Component.InvokeAsync("_ProductDetailFeatureComponentPartial", new { productId = ViewBag.ProductId })

    </div>
    <div class="row px-xl-5">
        <div class="col">
            <div class="bg-light p-30">
                <div class="nav nav-tabs mb-4">
                    <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Description</a>
                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Information</a>
                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews (1)</a>
                </div>
                <div class="tab-content">

                    @await Component.InvokeAsync("_ProductDetailDescriptionComponentPartial", new { productId = ViewBag.ProductId })
                    @await Component.InvokeAsync("_ProductDetailInformationComponentPartial", new { productId = ViewBag.ProductId })
                    @await Component.InvokeAsync("_ProductDetailReviewComponentPartial", new { productId = ViewBag.ProductId }) 
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Shop Detail End -->